SmartAdmin.Seed/Controllers/PrestadoresController.cs
#region Using

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Saludsa.UtilidadesRest;
using SistemaPedidos.Utilidades;
using SmartAdmin.Seed.Models.DTO;
using SmartAdminSaludsa.DBcontextPrestadores;
using SmartAdminSaludsa.Extensores;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

#endregion

namespace SmartAdminSaludsa.Controllers
{
    [Authorize]
    public class PrestadoresController : Controller
    {
        public IConfiguration Configuration { get; }
        private readonly PrestadoresContext db;

        public PrestadoresController(IConfiguration configuration, PrestadoresContext context)
        {
            Configuration = configuration;
            this.db = context;
        }

        #region Pedidos Actuales

        [Authorize(Policy = "Administracion")]
        public IActionResult Beneficios()
        {
            Log.WriteLog("", TypeError.Info, $"", Proceso: "Prestadores-Beneficios", usuario: User.Identity.Name);
            return View();
        }


        [Authorize(Policy = "Administracion")]
        public async Task<JsonResult>  ObtenerBeneficios(int? numeroConvenio, 
            string codigoProducto, 
            string codigoPlan, 
            int? versionPlan, int numeroPagina=1, int cantidadRegistros=50)
        {

            var idTRansaccion= Log.ObtenerIdTransaccion();
            var metodo = "Prestadores-ObtenerBeneficios";
            try
            {

                Log.WriteLog(idTRansaccion, 
                    TypeError.Info, 
                    $"parametros: Convenio-{numeroConvenio}, Prod-{codigoProducto}, Plan-{codigoPlan}, version-{versionPlan}",
                    Proceso: metodo, usuario: User.Identity.Name);

                var query = db.ConvenioPlan.AsQueryable();

                if (numeroConvenio.HasValue)
                    query = query.Where(x => x.NumeroConvenio== numeroConvenio.Value);

                if (!string.IsNullOrWhiteSpace(codigoProducto))
                    query = query.Where(x => x.CodigoProducto.Equals(codigoProducto.Trim(), StringComparison.InvariantCultureIgnoreCase));

                if (!string.IsNullOrWhiteSpace(codigoPlan))
                    query = query.Where(x => x.CodigoPlan.Equals(codigoPlan.Trim(), StringComparison.InvariantCultureIgnoreCase));

                if (versionPlan.HasValue)
                    query = query.Where(x => x.VersionPlan==versionPlan.Value);


                var resultado =  query.PaginateResult(numeroPagina,cantidadRegistros);

                Log.WriteLog(idTRansaccion, TypeError.Info, $"{Respuesta.OK}-Cantidad registros: {resultado.TotalRegistros}", Proceso: metodo);

                return new JsonResult(new RespuestaGenericaPaginada
                {
                    Estado = Respuesta.OK,
                    Resultado = resultado.Entidades.IsNull() ? new List<ConvenioPlan>() : resultado.Entidades,
                    TotalRegistros = resultado.Entidades.IsNull() ? 0 : resultado.TotalRegistros,
                    Mensaje = resultado.TotalRegistros == 0 ? "No existen " : string.Empty ,

                });

            }
            catch (Exception ex)
            {
                Log.WriteLog(idTRansaccion, TypeError.Error, $"Detalle error:{ex.Serializar()}",Proceso: metodo);

                return new JsonResult(new RespuestaGenericaPaginada
                {
                    Estado = Respuesta.Error,
                    TotalRegistros=0,
                    Mensaje = ex.Message,
                    Resultado = null,
                });
            }

        }
        #endregion
    }
}

SmartAdmin.Seed/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en-us" id="extr-page">
<head>
    <meta charset="utf-8" />

    <title>Saludsa</title>
    <meta name="description" content="Saludsa" />
    <meta name="author" content="Saludsa S.A" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Basic Styles -->
    @{ await Html.RenderPartialAsync("_StylesheetsPartial"); }

    <!-- FAVICONS -->
    <link rel="shortcut icon" href="~/img/logo_saludsa.png" type="image/x-icon" />
    <link rel="icon" href="~/img/logo_saludsa.png" type="image/x-icon" />

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700" />

    <!-- Specifying a Webpage Icon for Web Clip Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="~/img/splash/sptouch-icon-iphone.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/img/splash/touch-icon-ipad.png" />
    <link rel="apple-touch-icon" sizes="120x120" href="~/img/splash/touch-icon-iphone-retina.png" />
    <link rel="apple-touch-icon" sizes="152x152" href="~/img/splash/touch-icon-ipad-retina.png" />

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="~/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)" />
    <link rel="apple-touch-startup-image" href="~/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)" />
    <link rel="apple-touch-startup-image" href="~/img/splash/iphone.png" media="screen and (max-device-width: 320px)" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
</head>
<body class="animated fadeInDown">
    @{ await Html.RenderPartialAsync("_AuthHeader"); }
    <!-- MAIN PANEL -->
    <div id="main" role="main">
        <!-- MAIN CONTENT -->
        <div id="content" class="container">
            @RenderBody()
        </div>
        <!-- END MAIN CONTENT -->
    </div>
    <!-- END MAIN PANEL -->
    @{ await Html.RenderPartialAsync("_Scripts"); }
    @RenderSection("Scripts", required: false)
</body>
</html>

SmartAdmin.Seed/Views/Shared/_Footer.cshtml
<!-- PAGE FOOTER -->
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">Saludsa<span class="hidden-xs"> </span> © 2020</span>
        </div>
    </div>
</div>
<!-- END PAGE FOOTER -->

SmartAdmin.Seed/Views/Shared/_Header.cshtml
<!-- HEADER -->
<header id="header">
<div id="logo-group">
    <!-- PLACE YOUR LOGO HERE -->
    <span id="logo">
        <a href="/">
            @*<img src="~/img/logo.png" alt="SmartAdmin">*@
        </a>
    </span>
</div>

<!-- pulled right: nav area -->
<div class="pull-right">

    <!-- collapse menu button -->
    <div id="hide-menu" class="btn-header pull-right">
        <span>
            <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu">
                <i class="fa fa-reorder"></i>
            </a>
        </span>
    </div>
    <!-- end collapse menu -->
    <!-- #MOBILE -->
    <!-- Top menu profile link : this shows only when top menu is active -->
   

    <!-- logout button -->
    <div id="logout" class="btn-header transparent pull-right">
        <span>
            <a asp-controller="Account" asp-action="Logout" title="Salir" data-action="userLogout" data-logout-msg="&#191 Salir de la aplicaci&#243n ?">
                <i class="fa fa-sign-out"></i>
            </a>
        </span>
    </div>
   
</div>
<!-- end pulled right: nav area -->
</header>
<!-- END HEADER -->

SmartAdmin.Seed/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8" />

    <title>Saludsa</title>
    <meta name="description" content="Sasludsas" />
    <meta name="author" content="Saludsa S.A" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Basic Styles -->
    @{ await Html.RenderPartialAsync("_StylesheetsPartial"); }

    <!-- FAVICONS -->
    <link rel="shortcut icon" href="~/img/logo_saludsa.png" type="image/x-icon" />
    <link rel="icon" href="~/img/logo_saludsa.png" type="image/x-icon" />

    <!-- GOOGLE FONT -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,700" />

    <!-- Specifying a Webpage Icon for Web Clip Ref: https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html -->
    <link rel="apple-touch-icon" href="~/img/splash/sptouch-icon-iphone.png" />
    <link rel="apple-touch-icon" sizes="76x76" href="~/img/splash/touch-icon-ipad.png" />
    <link rel="apple-touch-icon" sizes="120x120" href="~/img/splash/touch-icon-iphone-retina.png" />
    <link rel="apple-touch-icon" sizes="152x152" href="~/img/splash/touch-icon-ipad-retina.png" />

    <!-- iOS web-app metas : hides Safari UI Components and Changes Status Bar Appearance -->
    <!-- Startup image for web apps -->
    <link rel="apple-touch-startup-image" href="~/img/splash/ipad-landscape.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)" />
    <link rel="apple-touch-startup-image" href="~/img/splash/ipad-portrait.png" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)" />
    <link rel="apple-touch-startup-image" href="~/img/splash/iphone.png" media="screen and (max-device-width: 320px)" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
</head>
<body class="smart-style-1">
    @{ await Html.RenderPartialAsync("_Header"); }
    @{ await Html.RenderPartialAsync("_Navigation"); }
    <!-- MAIN PANEL -->
    <div id="main" role="main">

        <!-- MAIN CONTENT -->
        <div id="content">
            
            <ol class="breadcrumb h6 fa-pull-left col col-lg-12">
                <li><a asp-action="Index" asp-controller="Home"><i class="fa fa-home"></i> Inicio</a></li>
                @RenderSection("Migas", required: false)
            </ol>
            @RenderBody()
        </div>
        <!-- END MAIN CONTENT -->
    </div>
    <!-- END MAIN PANEL -->
    @{ await Html.RenderPartialAsync("_Footer"); }
    @{ await Html.RenderPartialAsync("_Shortcuts"); }
    @{ await Html.RenderPartialAsync("_Scripts"); }
    <environment include="Development">
        <!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
        <script data-pace-options='{ "restartOnRequestAfter": true }' src="~/js/plugin/pace/pace.js"></script>

        <!-- Demo purpose only -->

    </environment>
    <environment exclude="Development">
        <!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
        <script data-pace-options='{ "restartOnRequestAfter": true }' src="~/js/plugin/pace/pace.min.js"></script>

        <!-- Demo purpose only -->
        @*<script src="~/js/demo.min.js" asp-append-version="true"></script>*@
    </environment>
    <script>
        $(function () {
            // DO NOT REMOVE : GLOBAL FUNCTIONS!
            pageSetUp();
        });
    </script>

    <span class="hide" id="span_mensaje">@TempData["Mensaje"]</span>
    <span class="hide" id="span_mensaje_timer">@TempData["MensajeTimer"]</span>
    @RenderSection("Scripts", required: false)
</body>
</html>

SmartAdmin.Seed/Views/Shared/_Navigation.cshtml
@using SmartAdmin.Seed.Configuration
@using SmartAdmin.Seed.Extensions
@inject IOptions<SmartSettings> Settings
<!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->
<aside id="left-panel">
    <!-- User info -->
    <!-- end user info -->
    <!-- NAVIGATION : This navigation is also responsive-->
    <nav>
        <!--
        NOTE: Notice the gaps after each icon usage <i></i>..
        Please note that these links work a bit different than
        traditional href="" links. See documentation for details.
        -->

        <ul>
            @{
                if (User.IsInRole(Perfiles.Administrador))
                {
                    <li is-active-route asp-controller="Prestadores">
                        <a href="#" title="Prestadores">
                            <i class="fa fa-lg fa-fw fa-address-book">
                            </i> <span class="menu-item-parent">Prestadores</span>
                        </a>
                        <ul>
                            <li is-active-route asp-controller="Prestadores" asp-action="Beneficios">
                                <a asp-controller="Prestadores"  asp-action="Beneficios" onclick="cargando()" title="Buscar beneficios">
                                    <i class="fa fa-lg fa-fw fa-search"></i>
                                    <span class="menu-item-parent">Buscar beneficios</span>
                                </a>
                            </li>
                            <li is-active-route asp-controller="Home" asp-action="PedidosHistoricos">
                                <a asp-controller="Home" onclick="cargando()" asp-action="PedidosHistoricos" title="Pedidos hist&#243ricos">
                                    <i class=""></i> <span>Pedidos hist&#243ricos</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    @*<li is-active-route asp-controller="Home">
                            <a href="#" title="Productos">
                                <i class="fa fa-lg fa-fw fa-tags"></i> <span class="menu-item-parent">Productos</span>
                            </a>

                            <ul>
                                <li is-active-route asp-controller="Home" asp-action="Productos">
                                    <a asp-controller="Home" onclick="cargando()" asp-action="Productos" title="Productos">
                                        <i class=""></i> <span>Productos</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li is-active-route asp-controller="Home">
                            <a href="#" title="informaci&oacute;n">
                                <i class="fa fa-lg fa-fw fa-bullhorn"></i> <span class="menu-item-parent">Anuncios</span>
                            </a>
                            <ul>
                                <li is-active-route asp-controller="Home" asp-action="Anuncios">
                                    <a asp-controller="Home" onclick="cargando()" asp-action="Anuncios" title="Anuncios">
                                        <i class=""></i> <span>Anuncios</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li is-active-route asp-controller="Home">
                            <a href="#" title="informaci&oacute;n">
                                <i class="fa fa-lg fa-fw fa-line-chart"></i> <span class="menu-item-parent">Reportes</span>
                            </a>
                            <ul>
                                <li is-active-route asp-controller="Home" asp-action="PanelInformacion">
                                    <a asp-controller="Home" onclick="cargando()" asp-action="PanelInformacion" title="Panel de informaci&oacute;n">
                                        <i class=""></i> <span>Panel de informaci&oacute;n</span>
                                    </a>
                                </li>
                            </ul>
                        </li>*@
                }
            }
        </ul>
    </nav>
    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>
</aside>
<!-- END NAVIGATION -->

SmartAdmin.Seed/Views/Shared/_Ribbon.cshtml
<!-- RIBBON -->
<div id="ribbon">

    <span class="ribbon-button-alignment">
        <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh" rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
            <i class="fa fa-refresh"></i>
        </span>
    </span>

    <!-- breadcrumb -->
    <ol class="breadcrumb">
        <li>Home</li>
        <li>Dashboard</li>
    </ol>
    <!-- end breadcrumb -->
    <!-- You can also add more buttons to the
    ribbon for further usability

    Example below:

    <span class="ribbon-button-alignment pull-right">
        <span id="search" class="btn btn-ribbon hidden-xs" data-title="search"><i class="fa-grid"></i> Change Grid</span>
        <span id="add" class="btn btn-ribbon hidden-xs" data-title="add"><i class="fa-plus"></i> Add</span>
        <span id="search" class="btn btn-ribbon" data-title="search">
            <i class="fa-search"></i> <span class="hidden-mobile">Search</span>
        </span>
    </span> -->

</div>
<!-- END RIBBON -->

SmartAdmin.Seed/Views/Shared/_Scripts.cshtml
<environment include="Development">
    <!-- NOTE: Enable the bundle for faster loading and optimized caching! -->
    <!-- <script src="~/js/smartadmin.min.js" asp-append-version="true"></script> -->
    <!-- Link to ASP.NET CDN's jQuery + jQueryUI; fall back to local -->
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.js" asp-fallback-src="~/js/libs/jquery-3.2.1.js" asp-fallback-test="window.jQuery" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.12.1/jquery-ui.js" asp-fallback-src="~/js/libs/jquery-ui-1.12.1.js" asp-fallback-test="window.jQuery && window.jQuery.ui" crossorigin="anonymous"></script>

    <!-- Link to ASP.NET CDN's Bootstrap; fall back to local -->
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.js" asp-fallback-src="~/js/bootstrap/bootstrap.js" asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal" crossorigin="anonymous"></script>

    <script src="~/js/Knockout/knockout-3.5.1.js"></script>

    <script src="~/js/waitMe/waitMe.min.js"></script>

    <!-- IMPORTANT: APP CONFIG -->
    <script src="~/js/app.config.js"></script>

    <!-- JS TOUCH : include this plugin for mobile drag / drop touch events-->
    <script src="~/js/plugin/jquery-touch/jquery.ui.touch-punch.js"></script>

    <!-- CUSTOM NOTIFICATION -->
    <script src="~/js/notification/SmartNotification.js"></script>

    <!-- JARVIS WIDGETS -->
    <script src="~/js/smartwidgets/jarvis.widget.js"></script>

    <!-- JQUERY MASKED INPUT -->
    <script src="~/js/plugin/masked-input/jquery.maskedinput.js"></script>

    <!-- JQUERY SELECT2 INPUT -->
    <script src="~/js/plugin/select2/select2.js"></script>

    <!-- JQUERY UI + Bootstrap Slider -->
    <script src="~/js/plugin/bootstrap-slider/bootstrap-slider.js"></script>

    <!-- Browser MSIE issue fix -->
    <script src="~/js/plugin/msie-fix/jquery.mb.browser.js"></script>

    <!-- FastClick: For mobile devices -->
    <script src="~/js/plugin/fastclick/fastclick.js"></script>

    <!-- MAIN APP JS FILE -->
    <script src="~/js/app.js"></script>

    <!-- ENHANCEMENT PLUGINS : NOT A REQUIREMENT -->
    <!-- Voice command : plugin -->
    <script src="~/js/speech/voicecommand.js"></script>

    <script src="~/js/app/site.js"></script>
    <script>
    $(document).ready(function () {
        pageSetUp();
        drawBreadCrumb();
        Gestionar_Msg();
        initLoadingForm();
         $.sound_path = "@Url.Content("~/sound/")";
    });
    </script>

    <!-- SmartChat UI : plugin -->
    <script src="~/js/smart-chat-ui/smart.chat.ui.js"></script>
    <script src="~/js/smart-chat-ui/smart.chat.manager.js"></script>

    <!-- PAGE RELATED PLUGIN(S) -->
    <!-- Full Calendar -->
    <script src="~/js/plugin/moment/moment.js"></script>
    <script src="~/js/plugin/fullcalendar/fullcalendar.js"></script>

    <!-- Easy pie charts -->
    <script src="~/js/plugin/easy-pie-chart/jquery.easy-pie-chart.js"></script>

    <!-- Sparklines -->
    <script src="~/js/plugin/sparkline/jquery.sparkline.js"></script>

    <!-- ChartJS -->
    <script src="~/js/plugin/chartjs/chart.js"></script>

    <!-- Flot Chart Plugin: Flot Engine, Flot Resizer, Flot Tooltip -->
    <script src="~/js/plugin/flot/jquery.flot.cust.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.resize.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.fillbetween.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.orderBar.min.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.pie.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.time.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.tooltip.js"></script>

    <!-- Vector Maps Plugin: Vectormap engine, Vectormap language -->
    <script src="~/js/plugin/vectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/js/plugin/vectormap/jquery-jvectormap-world-mill-en.js"></script>
</environment>
<environment exclude="Development">
    <!-- NOTE: Enable the bundle for faster loading and optimized caching! -->
    <!-- <script src="~/js/smartadmin.min.js" asp-append-version="true"></script> -->
    <!-- Link to ASP.NET CDN's jQuery + jQueryUI; fall back to local -->
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js" asp-fallback-src="~/js/libs/jquery-3.2.1.min.js" asp-fallback-test="window.jQuery" crossorigin="anonymous"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.ui/1.12.1/jquery-ui.min.js" asp-fallback-src="~/js/libs/jquery-ui-1.12.1.min.js" asp-fallback-test="window.jQuery && window.jQuery.ui" crossorigin="anonymous"></script>

    <!-- Link to ASP.NET CDN's Bootstrap; fall back to local -->
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js" asp-fallback-src="~/js/bootstrap/bootstrap.min.js" asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal" crossorigin="anonymous"></script>

    <script src="~/js/waitMe/waitMe.min.js"></script>
    <!-- IMPORTANT: APP CONFIG -->
    <script src="~/js/app.config.min.js"></script>

    <!-- JS TOUCH : include this plugin for mobile drag / drop touch events-->
    <script src="~/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script>

    <!-- CUSTOM NOTIFICATION -->
    <script src="~/js/notification/SmartNotification.min.js"></script>

    <!-- JARVIS WIDGETS -->
    <script src="~/js/smartwidgets/jarvis.widget.min.js"></script>

    <!-- JQUERY MASKED INPUT -->
    <script src="~/js/plugin/masked-input/jquery.maskedinput.min.js"></script>

    <!-- JQUERY SELECT2 INPUT -->
    <script src="~/js/plugin/select2/select2.min.js"></script>

    <!-- JQUERY UI + Bootstrap Slider -->
    <script src="~/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>

    <!-- Browser MSIE issue fix -->
    <script src="~/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>

    <!-- FastClick: For mobile devices -->
    <script src="~/js/plugin/fastclick/fastclick.min.js"></script>

    <!-- MAIN APP JS FILE -->
    <script src="~/js/app.min.js" asp-append-version="true"></script>

    <!-- ENHANCEMENT PLUGINS : NOT A REQUIREMENT -->
    <!-- Voice command : plugin -->
    <script src="~/js/speech/voicecommand.min.js"></script>

    <script src="~/js/app/site.js"></script>
    <script>
    $(document).ready(function () {
        pageSetUp();
        drawBreadCrumb();
        Gestionar_Msg();
        initLoadingForm();
         $.sound_path = "@Url.Content("~/sound/")";
    });
    </script>

    <!-- SmartChat UI : plugin -->
    <script src="~/js/smart-chat-ui/smart.chat.ui.min.js"></script>
    <script src="~/js/smart-chat-ui/smart.chat.manager.min.js"></script>

    <!-- PAGE RELATED PLUGIN(S) -->
    <!-- Full Calendar -->
    <script src="~/js/plugin/moment/moment.min.js"></script>
    <script src="~/js/plugin/fullcalendar/fullcalendar.min.js"></script>

    <!-- Easy pie charts -->
    <script src="~/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>

    <!-- Sparklines -->
    <script src="~/js/plugin/sparkline/jquery.sparkline.min.js"></script>

    <!-- ChartJS -->
    <script src="~/js/plugin/chartjs/chart.min.js"></script>

    <!-- Flot Chart Plugin: Flot Engine, Flot Resizer, Flot Tooltip -->
    <script src="~/js/plugin/flot/jquery.flot.cust.min.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.resize.min.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.fillbetween.min.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.orderBar.min.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.pie.min.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.time.min.js"></script>
    <script src="~/js/plugin/flot/jquery.flot.tooltip.min.js"></script>

    <!-- Vector Maps Plugin: Vectormap engine, Vectormap language -->
    <script src="~/js/plugin/vectormap/jquery-jvectormap-1.2.2.min.js"></script>
    <script src="~/js/plugin/vectormap/jquery-jvectormap-world-mill-en.js"></script>
</environment>

<!-- JQUERY VALIDATE -->
@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

<!--[if IE 8]>
    <h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>
<![endif]-->